# WARNING: Do not deploy this tutorial configuration directly to a production environment
#
# The tutorial docker-compose files have not been written for production deployment and will not 
# scale. A proper architecture has been sacrificed to keep the narrative focused on the learning 
# goals, they are just used to deploy everything onto a single Docker machine. All FIWARE components 
# are running at full debug and extra ports have been exposed to allow for direct calls to services. 
# They also contain various obvious security flaws - passwords in plain text, no load balancing,
# no use of HTTPS and so on. 
# 
# This is all to avoid the need of multiple machines, generating certificates, encrypting secrets
# and so on, purely so that a single docker-compose file can be read as an example to build on, 
# not use directly. 
# 
# When deploying to a production environment, please refer to the Helm Repository
# for FIWARE Components in order to scale up to a proper architecture:
# 
# see: https://github.com/FIWARE/helm-charts/
#
services:
  # @context file is served from here
  ld-context:
    labels:
      org.fiware: 'tutorial'
    image: httpd:alpine
    hostname: context
    container_name: fiware-ld-context
    ports:
        - "3004:80"
    volumes:
        - data-models:/usr/local/apache2/htdocs/
        - type: bind
          source: ${PWD}/conf/mime.types
          target: /usr/local/apache2/conf/mime.types
          read_only: true
    healthcheck:
      test: (wget --server-response --spider --quiet  http://context/user-context.jsonld 2>&1 | awk 'NR==1{print $$2}'|  grep -q -e "200") || exit 1

  # Databases
  mongo-db:
    labels:
      org.fiware: 'tutorial'
    image: mongo:${MONGO_DB_VERSION}
    hostname: mongo-db
    container_name: db-mongo
    ports:
      - "${MONGO_DB_PORT}:${MONGO_DB_PORT}" # localhost:27017
    networks:
      - default
    command: --nojournal
    volumes:
      - mongo-db:/data
    healthcheck:
      test: ["CMD","mongosh", "localhost:27017/test", "--quiet"]
      interval: 5s

  mysql-config-db:
    labels:
      org.fiware: 'tutorial'
    image: "mysql:${MYSQL_DB_VERSION}"
    hostname: mysql-config-db
    container_name: db-mysql-config
    environment:
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=password"
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=db"
    restart: "always"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    networks:
      - default
    volumes:
       - mysql-config-db:/var/lib/mysql
       - ../mysql-data:/docker-entrypoint-initdb.d/:ro # Preload Trusted Issuers

  mysql-trust-db:
    labels:
      org.fiware: 'tutorial'
    image: "mysql:${MYSQL_DB_VERSION}"
    hostname: mysql-trust-db
    container_name: db-mysql-trust
    environment:
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=password"
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=db"
    restart: "always"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    networks:
      - default
    volumes:
       - mysql-trust-db:/var/lib/mysql



  # A series of dummy IoT Sensors over HTTP
  iot-sensors:
    labels:
      org.fiware: 'tutorial'
    image: quay.io/fiware/tutorials.iot-devices
    hostname: iot-sensors
    container_name: fiware-iot-devices
    networks:
      - default
    expose:
      - "${TUTORIAL_DUMMY_DEVICE_PORT}"
    ports:
      - "${TUTORIAL_DUMMY_DEVICE_PORT}:${TUTORIAL_DUMMY_DEVICE_PORT}" # localhost:3001
    environment:
      - DEBUG=devices:*
      - WEB_APP_HOST=tutorial
      - WEB_APP_PORT=${TUTORIAL_APP_PORT} # Port used by the content provider proxy and web-app for viewing data
      - IOTA_HTTP_HOST=iot-agent
      - IOTA_HTTP_PORT=${IOTA_SOUTH_PORT}
      - PIG_COUNT=${PIG_COUNT}
      - COW_COUNT=${COW_COUNT}





  credentials-config:
    labels:
      org.fiware: 'tutorial'
    image: quay.io/fiware/credentials-config-service:${CONFIG_SERVICE_VERSION}
    hostname: credentials-config
    container_name: fiware-credentials-config
    environment:
      DATASOURCES_DEFAULT_URL: "jdbc:mysql://mysql-config-db:3306/db"
      DATASOURCES_DEFAULT_DRIVER_CLASS_NAME: "com.mysql.cj.jdbc.Driver"
      DATASOURCES_DEFAULT_USERNAME: "user"
      DATASOURCES_DEFAULT_PASSWORD: "password"
      DATASOURCES_DEFAULT_DIALECT: "MYSQL"
    ports:
      - "8081:8080"
    restart: "always"
    healthcheck:
      test: ["CMD", "ping", "localhost"]
      timeout: 5s
      retries: 10
    depends_on:
      mysql-config-db:
        condition: service_healthy
    networks:
      - default


  trusted-issuers-list:
    labels:
      org.fiware: 'tutorial'
    image: quay.io/fiware/trusted-issuers-list:${TRUSTED_ISSUERS_VERSION}
    hostname: trusted-issuers-list
    container_name: fiware-trusted-issuers-list
    environment:
      DATASOURCES_DEFAULT_URL: "jdbc:mysql://mysql-trust-db:3306/db"
      DATASOURCES_DEFAULT_DRIVER_CLASS_NAME: "com.mysql.cj.jdbc.Driver"
      DATASOURCES_DEFAULT_USERNAME: "user"
      DATASOURCES_DEFAULT_PASSWORD: "password"
      DATASOURCES_DEFAULT_DIALECT: "MYSQL"
    ports:
      - "8080:8080"
    restart: "always"
    depends_on:
      mysql-trust-db:
        condition: service_healthy
    networks:
      - default


  # Tutorial acts as a Farm Management Information System
  tutorial:
    labels:
      org.fiware: 'tutorial'
    image: quay.io/fiware/tutorials.ngsi-ld
    hostname: tutorial
    container_name: fiware-tutorial
    depends_on:
      mongo-db:
        condition: service_healthy
    networks:
      - default
    expose:
      - "${TUTORIAL_APP_PORT}"
    ports:
      - "${TUTORIAL_APP_PORT}:${TUTORIAL_APP_PORT}" # localhost:3000
    environment:
      - DEBUG=tutorial:*
      - WEB_APP_PORT=${TUTORIAL_APP_PORT} # Port used by the content provider proxy and web-app for viewing data
      - IOTA_HTTP_HOST=iot-agent
      - IOTA_HTTP_PORT=${IOTA_SOUTH_PORT}
      - DUMMY_DEVICES=http://iot-sensors:3001
      - MONGO_URL=mongodb://mongo-db:27017
      - IOTA_JSON_LD_CONTEXT=http://context/user-context.jsonld
      - NGSI_LD_TENANT=openiot


  # IoT-Agent is configured for the UltraLight Protocol
  iot-agent:
    labels:
      org.fiware: 'tutorial'
    image: quay.io/fiware/iotagent-ul:${ULTRALIGHT_VERSION}
    hostname: iot-agent
    container_name: fiware-iot-agent
    depends_on:
      mongo-db:
        condition: service_healthy
    networks:
      - default
    expose:
      - "${IOTA_NORTH_PORT}"
      - "${IOTA_SOUTH_PORT}"
    ports:
      - "${IOTA_NORTH_PORT}:${IOTA_NORTH_PORT}" # localhost:4041
      - "${IOTA_SOUTH_PORT}:${IOTA_SOUTH_PORT}" # localhost:7896
    environment:
      - IOTA_NORTH_PORT=${IOTA_NORTH_PORT}
      - IOTA_REGISTRY_TYPE=mongodb #Whether to hold IoT device info in memory or in a database
      - IOTA_LOG_LEVEL=DEBUG # The log level of the IoT Agent
      - IOTA_TIMESTAMP=true # Supply timestamp information with each measurement
      - IOTA_AUTOCAST=true # Ensure Ultralight number values are read as numbers not strings
      - IOTA_MONGO_HOST=mongo-db # The host name of MongoDB
      - IOTA_MONGO_PORT=${MONGO_DB_PORT} # The port mongoDB is listening on
      - IOTA_MONGO_DB=iotagentul # The name of the database used in mongoDB
      - IOTA_HTTP_PORT=${IOTA_SOUTH_PORT} # The port used for device traffic over HTTP
      - IOTA_PROVIDER_URL=http://iot-agent:${IOTA_NORTH_PORT}
      - IOTA_CB_NGSI_VERSION=ld # use NGSI-LD when sending updates for active attributes
      - IOTA_JSON_LD_CONTEXT=http://context/user-context.jsonld
      - IOTA_FALLBACK_TENANT=openiot
      - IOTA_MULTI_CORE=true
    healthcheck:
      interval: 5s

  farmer:
    labels:
      org.fiware: 'tutorial'
    image: quay.io/fiware/tutorials.forwarder
    hostname: 'farmer'
    container_name: cb-farmer
    ports:
      - 1027:80
    networks:
      - default
    environment:
      - TENANT=farmer
      - DEBUG=broker:*

  devices:
    labels:
      org.fiware: 'tutorial'
    image: quay.io/fiware/tutorials.forwarder
    hostname: 'devices'
    container_name: cb-devices
    networks:
      - default
    ports:
      - 1028:80
    environment:
      - TENANT=openiot
      - DEBUG=broker:*

  contractor:
    labels:
      org.fiware: 'tutorial'
    image: quay.io/fiware/tutorials.forwarder
    hostname: 'contractor'
    container_name: cb-contractor
    networks:
      - default
    ports:
      - 1029:80
    environment:
      - TENANT=contractor
      - DEBUG=broker:*

  vet:
    labels:
      org.fiware: 'tutorial'
    image: quay.io/fiware/tutorials.forwarder
    hostname: 'vet'
    container_name: cb-vet
    networks:
      - default
    depends_on:
      credentials-config:
        condition: service_started
    ports:
      - 1030:80
    environment:
      - TENANT=vet
      - DEBUG=broker:*
      - VERIFY_CREDENTIALS=true
      - CONFIG_SERVICE=credentials-config:8080
      - WEB_APP_HOST=tutorial
      - WEB_APP_PORT=${TUTORIAL_APP_PORT}

  weather:
    labels:
      org.fiware: 'tutorial'
    image: quay.io/fiware/tutorials.forwarder
    hostname: 'vet'
    container_name: cb-weather
    networks:
      - default
    ports:
      - 1031:80
    environment:
      - TENANT=weather
      - DEBUG=broker:*

networks:
  default:
    labels:
      org.fiware: 'tutorial'

volumes:
  mongo-db: ~
  mongo-config: ~
  mysql-trust-db: ~
  mysql-config-db: ~
  data-models:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data-models
